# Generated by Django 2.0.1 on 2018-03-27 06:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('site', models.URLField()),
                ('site_categories', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('published', models.DateTimeField()),
                ('site_type', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('main_image', models.URLField()),
                ('performance_score', models.PositiveSmallIntegerField()),
                ('domain_rank', models.PositiveSmallIntegerField()),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('language', models.CharField(max_length=30)),
                ('entities', models.TextField()),
                ('social', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('query', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='tracker',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.TrackerCategory'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Tracker'),
        ),
    ]
