# Generated by Django 2.0.3 on 2018-04-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20180402_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='site',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
