# Generated by Django 2.0.3 on 2018-04-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20180402_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='domain_rank',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
