# Generated by Django 2.0.1 on 2018-04-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_tracker_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='last_modified',
            field=models.DateTimeField(),
        ),
    ]
