# Generated by Django 2.0.1 on 2018-04-18 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20180418_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tracker',
            new_name='trackers',
        ),
    ]
