# Generated by Django 2.0.1 on 2018-04-25 06:55

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_auto_20180418_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='search_document',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_document'], name='tracker_pos_search__3e906b_gin'),
        ),
    ]
