# Generated by Django 2.0.1 on 2018-04-30 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_auto_20180425_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevancy', models.PositiveSmallIntegerField(default=0)),
                ('read', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.User')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.ManyToManyField(through='tracker.UserPost', to='tracker.Post'),
        ),
    ]
