# Generated by Django 2.0.1 on 2018-05-02 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_auto_20180502_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPostRelevant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevancy', models.PositiveSmallIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Post')),
            ],
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='posts',
        ),
        migrations.AddField(
            model_name='user',
            name='readPosts',
            field=models.ManyToManyField(related_name='readPosts', to='tracker.Post'),
        ),
        migrations.DeleteModel(
            name='UserPost',
        ),
        migrations.AddField(
            model_name='userpostrelevant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='releventPosts',
            field=models.ManyToManyField(related_name='relevantPosts', through='tracker.UserPostRelevant', to='tracker.Post'),
        ),
    ]
