# Generated by Django 2.0.1 on 2018-05-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_auto_20180502_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='readPosts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='releventPosts',
        ),
        migrations.AddField(
            model_name='user',
            name='read_posts',
            field=models.ManyToManyField(related_name='read_posts', to='tracker.Post'),
        ),
        migrations.AddField(
            model_name='user',
            name='relevent_posts',
            field=models.ManyToManyField(related_name='relevant_posts', through='tracker.UserPostRelevant', to='tracker.Post'),
        ),
    ]
