# Generated by Django 2.0.1 on 2018-05-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_auto_20180502_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostrelevant',
            name='relevancy',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Default'), (1, 'Starred'), (2, 'Irrelevant')], default=0),
        ),
    ]
