# Generated by Django 2.0.1 on 2018-05-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_auto_20180522_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='post',
            name='site_full',
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(max_length=1024),
        ),
    ]
