# Generated by Django 2.0.1 on 2018-05-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_auto_20180522_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
