# Generated by Django 2.0.1 on 2018-05-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_auto_20180522_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.URLField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='site_full',
            field=models.URLField(max_length=512),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(max_length=512),
        ),
    ]
